nelmio_api_doc:
    documentation:
        info:
            title: API Bilemo
            description: Découvrez notre sélection de téléphones mobiles haut de gamme.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []

# Begin of manual endpoint definition  
#####################################
        paths:
          /api/login_check:
            post:
              tags:
                - Login
              description: Login with client's credentials.
              requestBody:
                description: Json body
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        username:
                          type: string
                          example: 'testuser'
                        password:
                          type: string
                          example: 'testuser'
              responses:
                '200':
                  description: Login successful
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          token:
                            type: string


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
